version: '3.1'

services:
  
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: P@ssword!123
  
  coredemo2:
    build:
      context: .
    image: coredemo:latest
    ports:
      - "8000:80"
    depends_on:
            - db
    environment:
      ASPNETCORE_ENVIRONMENT: Prod
